log:
  log_dir: 'log'
  chkpt_dir: 'chkpt'


arcface:
  chkpt_path: 'Arcface.pth'
  vector_size: 256

data:
  dataset_dir: '/mnt/storage_2/project_data/grant_505/faceshifter-datasets-preprocessed/train'
  valset_dir: '/mnt/storage_2/project_data/grant_505/faceshifter-datasets-preprocessed/val'
  lowres: false

model:
  learning_rate_E_G: 4e-4
  learning_rate_D: 4e-4

  beta1: 0
  beta2: 0.999

  batch_size: 8

  num_workers: 16
  grad_clip: 0.0
